version: '3'
services:
  app:
    build: Docker/php
    container_name: PC_PHP
    volumes:
      - ./:/var/www
  nginx:
    image: nginx:1.17
    container_name: PC_nginx
    ports:
      - 8011:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/skillup.local.conf:/etc/nginx/conf.d/skillup.local.conf
    depends_on:
      - app